export default [
  {
    metadataListExpectedResult: [
      {
        brand: "Toyota",
        id: "CATEGORY#SURVEY",
        categoryName: "survey",
        startDate: "01-05-2021",
        endDate: "05-05-2021",
        description: "This is an updated sample description that got rejected",
        alternateEmailIdFlag: true,
        comments: [
          {
            time: "09/07/2021 08:33pm",
            user: "abc@xyz.com",
            comment: "Sample Comment 1",
          },
        ],
        ModifiedDate: "10-05-2021",
        ModifiedBy: "100",
        CreatedDate: "15-05-2021",
        Status: "rejected",
        rank: 2,
        Level: 1,
      },
      {
        brand: "Toyota",
        id: "CATEGORY#MARKETING",
        categoryName: "Marketing",
        startDate: "01-05-2021",
        endDate: "05-05-2021",
        description: "This is an updated sample description that got rejected",
        alternateEmailIdFlag: true,

        comments: [
          {
            time: "09/07/2021 08:33pm",
            user: "abc@xyz.com",
            comment: "Sample Comment 1",
          },
        ],
        ModifiedDate: "10-05-2021",
        ModifiedBy: "100",
        CreatedDate: "15-05-2021",
        Status: "rejected",
        rank: 1,
        Level: 1,
        subCategory: [
          {
            brand: "Toyota",
            id: "CATEGORY#MARKETING#SERVICE_COMMUNICATION",
            subCategoryName: "Service Communications",
            modeOfCommunication: {
              email: true,
              mail: true,
              call: false,
              sms: false,
              default: [],
            },
            ModifiedDate: "22-05-2021",
            ModifiedBy: "102",
            CreatedDate: "25-05-2021",
            Status: "rejected",
            startDate: "01-05-2021",
            endDate: "05-05-2021",
            rank: 1,
            Level: 2,
            subCategory: [
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#SERVICE_COMMUNICATION#NATIONAL_SERVICE_PROMATIONS",
                subCategoryName: "nationalServicePromations",
                ModifiedDate: "22-05-2021",
                ModifiedBy: "102",
                CreatedDate: "25-05-2021",
                Status: "rejected",
                startDate: "01-06-2021",
                endDate: "05-06-2021",
                rank: 1,
                Level: 3,
              },
            ],
          },
          {
            brand: "Toyota",
            id: "CATEGORY#MARKETING#VEHICLE_COMMUNICATION",
            subCategoryName: "Vehicle Communication",
            modeOfCommunication: {
              email: true,
              mail: true,
              call: false,
              sms: false,
              default: [],
            },
            ModifiedDate: "18-05-2021",
            ModifiedBy: "101",
            CreatedDate: "20-05-2021",
            Status: "rejected",
            startDate: "01-05-2021",
            endDate: "05-05-2021",
            rank: 2,
            Level: 2,
            subCategory: [
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#VEHICLE_COMMUNICATION#SALES_EVENT",
                subCategoryName: "salesEvents",
                ModifiedDate: "18-05-2021",
                ModifiedBy: "101",
                CreatedDate: "20-05-2021",
                Status: "rejected",
                startDate: "01-06-2021",
                endDate: "05-06-2021",
                rank: 1,
                Level: 3,
              },
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#VEHICLE_COMMUNICATION#NEWS_LETTER",
                subCategoryName: "newsLetter",
                ModifiedDate: "18-05-2021",
                ModifiedBy: "101",
                CreatedDate: "20-05-2021",
                Status: "rejected",
                startDate: "01-05-2021",
                endDate: "05-05-2021",
                rank: 2,
                Level: 3,
              },
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#VEHICLE_COMMUNICATION#NEW_PRODUCT_REVEALS_AND_NEWS",
                subCategoryName: "newProductRevealsAndNews",
                ModifiedDate: "18-05-2021",
                ModifiedBy: "101",
                CreatedDate: "20-05-2021",
                Status: "rejected",
                startDate: "01-06-2021",
                endDate: "05-06-2021",
                rank: 3,
                Level: 3,
              },
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#VEHICLE_COMMUNICATION#OWNER_COMMUNICATION",
                subCategoryName: "ownerCommunications",
                ModifiedDate: "18-05-2021",
                ModifiedBy: "101",
                CreatedDate: "20-05-2021",
                Status: "rejected",
                startDate: "01-06-2021",
                endDate: "05-06-2021",
                rank: 4,
                Level: 3,
              },
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#VEHICLE_COMMUNICATION#SHOPPING_COMMUNICATION",
                subCategoryName: "shoppingCommunications",
                ModifiedDate: "18-05-2021",
                ModifiedBy: "101",
                CreatedDate: "20-05-2021",
                Status: "rejected",
                startDate: "01-06-2021",
                endDate: "05-06-2021",
                rank: 5,
                Level: 3,
              },
            ],
          },
          {
            brand: "Toyota",
            id: "CATEGORY#MARKETING#PREFERENCES",
            subCategoryName: "Preferences",
            ModifiedDate: "09-09-2020",
            ModifiedBy: "300",
            CreatedDate: "10-08-2020",
            Status: "rejected",
            startDate: "01-02-2021",
            endDate: "05-04-2021",
            Level: 1,
            subCategory: [
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#PREFERENCES#LIFE_STYLE",
                subCategoryName: "Life style",
                ModifiedDate: "10-09-2019",
                ModifiedBy: "200",
                CreatedDate: "15-09-2019",
                Status: "rejected",
                startDate: "01-05-2021",
                endDate: "05-05-2021",
                rank: 1,
                Level: 2,
                subCategory: [
                  {
                    brand: "Toyota",
                    id: "CATEGORY#MARKETING#PREFERENCES#LIFE_STYLE#SPORTS",
                    subCategoryName: "sports",
                    ModifiedDate: "11-09-2020",
                    ModifiedBy: "201",
                    CreatedDate: "16-08-2020",
                    Status: "rejected",
                    startDate: "01-07-2021",
                    endDate: "05-07-2021",
                    rank: 1,
                    Level: 4,
                  },
                  {
                    brand: "Toyota",
                    id: "CATEGORY#MARKETING#PREFERENCES#LIFE_STYLE#TRAVEL",
                    subCategoryName: "travel",
                    ModifiedDate: "14-08-2020",
                    ModifiedBy: "202",
                    CreatedDate: "20-08-2020",
                    Status: "rejected",
                    startDate: "01-06-2021",
                    endDate: "05-06-2021",
                    rank: 2,
                    Level: 3,
                  },
                ],
              },
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST",
                subCategoryName: "vehicleOfIntrest",
                ModifiedDate: "07-09-2029",
                ModifiedBy: "301",
                CreatedDate: "7-07-2020",
                Status: "rejected",
                imageFlag: false,
                startDate: "01-05-2021",
                endDate: "05-05-2021",
                rank: 2,
                Level: 2,
                subCategory: [
                  {
                    brand: "Toyota",
                    id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CARS_AND_MINIVAN",
                    subCategoryName: "carsAndMinivan",
                    ModifiedDate: "13-09-2020",
                    ModifiedBy: "400",
                    CreatedDate: "24-09-2020",
                    Status: "rejected",
                    imageFlag: false,
                    startDate: "01-06-2021",
                    endDate: "05-06-2021",
                    rank: 1,
                    Level: 3,
                    subCategory: [
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CARS_AND_MINIVAN#COROLLA",
                        subCategoryName: "corolla",
                        ModifiedDate: "13-09-2020",
                        ModifiedBy: "402",
                        CreatedDate: "24-09-2020",
                        Status: "rejected",
                        startDate: "01-07-2021",
                        endDate: "05-07-2021",
                        rank: 1,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CARS_AND_MINIVAN#YARIS",
                        subCategoryName: "yaris",
                        ModifiedDate: "13-09-2020",
                        ModifiedBy: "401",
                        CreatedDate: "24-09-2020",
                        Status: "rejected",
                        startDate: "01-07-2021",
                        endDate: "05-07-2021",
                        rank: 2,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CARS_AND_MINIVAN#Camry",
                        subCategoryName: "camry",
                        ModifiedDate: "13-09-2020",
                        ModifiedBy: "403",
                        CreatedDate: "24-09-2020",
                        Status: "rejected",
                        startDate: "01-07-2021",
                        endDate: "05-07-2021",
                        rank: 3,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CARS_AND_MINIVAN#MATRIX",
                        subCategoryName: "matrix",
                        ModifiedDate: "13-09-2020",
                        ModifiedBy: "404",
                        CreatedDate: "24-09-2020",
                        Status: "rejected",
                        startDate: "01-07-2021",
                        endDate: "05-07-2021",
                        rank: 4,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CARS_AND_MINIVAN#SIENNA",
                        subCategoryName: "sienna",
                        ModifiedDate: "13-09-2020",
                        ModifiedBy: "404",
                        CreatedDate: "24-09-2020",
                        Status: "rejected",
                        startDate: "01-07-2021",
                        endDate: "05-07-2021",
                        rank: 5,
                        Level: 4,
                      },
                    ],
                  },
                  {
                    brand: "Toyota",
                    id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#TRUCKS",
                    subCategoryName: "trucks",
                    ModifiedDate: "4-09-2020",
                    ModifiedBy: "405",
                    CreatedDate: "07-09-2020",
                    Status: "rejected",
                    imageFlag: false,
                    startDate: "01-06-2021",
                    endDate: "05-06-2021",
                    rank: 2,
                    Level: 3,
                  },
                  {
                    brand: "Toyota",
                    id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#tacoma",
                    subCategoryName: "tacoma",
                    ModifiedDate: "18-09-2020",
                    ModifiedBy: "406",
                    CreatedDate: "9-9-2020",
                    Status: "rejected",
                    startDate: "01-07-2021",
                    endDate: "05-06-2021",
                    rank: 2,
                    Level: 4,
                  },
                  {
                    brand: "Toyota",
                    id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#TUNDRA",
                    subCategoryName: "tundra",
                    ModifiedDate: "18-09-2020",
                    ModifiedBy: "407",
                    CreatedDate: "9-9-2020",
                    Status: "rejected",
                    startDate: "01-08-2021",
                    endDate: "05-09-2021",
                    rank: 3,
                    Level: 4,
                  },
                  {
                    brand: "Toyota",
                    id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CROSS_OVER_AND_SUV",
                    subCategoryName: "crossoversAndSUV",
                    ModifiedDate: "18-09-2021",
                    ModifiedBy: "500",
                    CreatedDate: "7-9-1999",
                    Status: "rejected",
                    imageFlag: false,
                    startDate: "01-06-2021",
                    endDate: "05-05-2021",
                    rank: 3,
                    Level: 3,
                    subCategory: [
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CROSS_OVER_AND_SUV#RAVA",
                        subCategoryName: "rava",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "408",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-08-2021",
                        endDate: "05-05-2021",
                        rank: 3,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CROSS_OVER_AND_SUV#SIENNA",
                        subCategoryName: "sienna",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "409",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-08-2021",
                        endDate: "05-05-2021",
                        rank: 4,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CROSS_OVER_AND_SUV#HIGHLANDER",
                        subCategoryName: "highlander",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "501",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-04-2021",
                        endDate: "05-03-2021",
                        rank: 5,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CROSS_OVER_AND_SUV#VENDRA",
                        subCategoryName: "venza",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "502",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-05-2021",
                        endDate: "05-05-2021",
                        rank: 6,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#CROSS_OVER_AND_SUV#SQWUAIA",
                        subCategoryName: "swquaia",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "502",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-05-2021",
                        endDate: "05-05-2021",
                        rank: 6,
                        Level: 4,
                      },
                    ],
                  },
                  {
                    brand: "Toyota",
                    id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#HYBRID_AND_FULE_CELL",
                    subCategoryName: "hybridsAndFuleCell",

                    ModifiedDate: "09-09-2022",
                    ModifiedBy: "800",
                    CreatedDate: "8-8-2000",
                    Status: "rejected",
                    imageFlag: false,
                    startDate: "01-05-2021",
                    endDate: "05-05-2021",
                    rank: 4,
                    Level: 3,
                    subCategory: [
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#HYBRID_AND_FULE_CELL#2022PriusPrime",
                        subCategoryName: "2022PriusPrime",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "504",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-05-2021",
                        endDate: "05-05-2021",
                        rank: 4,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#HYBRID_AND_FULE_CELL#2021HighlanderHybrid",
                        subCategoryName: "2021HighlanderHybrid",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "505",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-05-2021",
                        endDate: "05-05-2021",
                        rank: 5,
                        Level: 4,
                      },
                    ],
                  },
                  {
                    brand: "Toyota",
                    id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#UPCOMING_VEHICLES",
                    subCategoryName: "upcomingVehicles",

                    ModifiedDate: "10-08-2020",
                    ModifiedBy: "600",
                    CreatedDate: "6-8-2022",
                    Status: "rejected",
                    imageFlag: false,
                    startDate: "01-05-2021",
                    endDate: "05-05-2021",
                    rank: 5,
                    Level: 3,
                    subCategory: [
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#UPCOMING_VEHICLES#grSupraA91CfEdition",
                        subCategoryName: "grSupraA91CfEdition",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "505",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-05-2021",
                        endDate: "05-05-2021",
                        rank: 5,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#UPCOMING_VEHICLES#toyotaBZ4XConsept",
                        subCategoryName: "toyotaBZ4XConsept",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "505",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-05-2021",
                        endDate: "05-05-2021",
                        rank: 6,
                        Level: 4,
                      },
                      {
                        brand: "Toyota",
                        id: "CATEGORY#MARKETING#PREFERENCES#VEHICLE_OF_INTREST#UPCOMING_VEHICLES#2021HighlanderHybrid",
                        subCategoryName: "gr86",
                        ModifiedDate: "18-09-2020",
                        ModifiedBy: "505",
                        CreatedDate: "9-9-2020",
                        Status: "rejected",
                        startDate: "01-05-2021",
                        endDate: "05-05-2021",
                        rank: 7,
                        Level: 4,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            brand: "Toyota",
            id: "CATEGORY#MARKETING#VEHICLE_CONNECTED_SERVICES",
            subCategoryName: "vehicleConnectedServices",
            modeOfCommunication: {
              email: true,
              mail: true,
              call: false,
              sms: false,
              default: [],
            },
            ModifiedDate: "29-05-2021",
            ModifiedBy: "103",
            CreatedDate: "31-05-2021",
            Status: "rejected",
            startDate: "01-05-2021",
            endDate: "05-05-2021",
            rank: 4,
            Level: 2,
            subCategory: [
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#VEHICLE_CONNECTED_SERVICES#NEW_PRODUCT_LAUNCHES",
                subCategoryName: "newProductLaunches",

                ModifiedDate: "29-05-2021",
                ModifiedBy: "103",
                CreatedDate: "31-05-2021",
                Status: "rejected",
                rank: 2,
                Level: 3,
              },
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#VEHICLE_CONNECTED_SERVICES#TRIAL_ENGAGEMENT",
                subCategoryName: "trialEngagement",
                ModifiedDate: "29-05-2021",
                ModifiedBy: "103",
                CreatedDate: "31-05-2021",
                Status: "rejected",
                startDate: "01-05-2021",
                endDate: "05-05-2021",
                rank: 3,
                Level: 3,
              },
              {
                brand: "Toyota",
                id: "CATEGORY#MARKETING#VEHICLE_CONNECTED_SERVICES#SEASONAL_ENGAGEMENT",
                subCategoryName: "seasonalEngagement",
                ModifiedDate: "29-05-2021",
                ModifiedBy: "103",
                CreatedDate: "31-05-2021",
                Status: "rejected",
                startDate: "01-05-2021",
                endDate: "05-05-2021",
                rank: 4,
                Level: 3,
              },
            ],
          },
        ],
      },
    ],
  },
];
